language: java

jdk:
  - oraclejdk8

script: ./build.sh

notifications:
  email:
    recipients:
      - fishercoder@gmail.com
      - steve.j.sun@gmail.com
    on_success: always
    on_failure: always

